### PR TITLE
Use the media type framework provided by EAT-mediatypes 

### LINKED ISSUE #65: EAT media types naming convention
The [EAT media types draft](https://datatracker.ietf.org/doc/draft-ietf-rats-eat-media-type/) has been recently adopted.  We should adopt the same naming convention.

### PR DESCRIPTION
**Pull request by thomas-fossati**
Fix #65

### CODE REVIEW

**Comment by thomas-fossati** [comment]
@adrianlshaw @hannestschofenig @SimonFrost-Arm is there any push back merging this?

**Comment by adrianlshaw** [comment]
I don't know much about media types but LGTM

**Comment by SimonFrost-Arm** [comment]
LGTM

**Comment by thomas-fossati** [comment]
thanks!

**Pull request merged**
