### PR TITLE
PSA attester description

### LINKED ISSUE #55: Add a description of the PSA attester as per RATS architecture
Provide a description of the PSA attester according to the conceptual model defined in [Section 3.1 of RATS](https://datatracker.ietf.org/doc/html/draft-ietf-rats-architecture-16#section-3.1).

### PR DESCRIPTION
**Pull request by thomas-fossati**
Fix #55

Signed-off-by: Thomas Fossati <thomas.fossati@arm.com>

### CODE REVIEW

**Review by SimonFrost-Arm — APPROVED** [review]
LGTM

**Review by adrianlshaw — APPROVED** [review]
LGTM as well. I think some people may ask what we mean by "Initial attestation service". Maybe it's worth an extra sentence. The closest concept is an Initial DevID (IDevID) but also very restricted.

**Comment by thomas-fossati** [comment]
> LGTM as well. I think some people may ask what we mean by "Initial attestation service". Maybe it's worth an extra sentence. The closest concept is an Initial DevID (IDevID) but also very restricted.

Thanks Adrian.  I've opened #57 to track your comment.

**Comment by thomas-fossati** [comment]
> > LGTM as well. I think some people may ask what we mean by "Initial attestation service". Maybe it's worth an extra sentence. The closest concept is an Initial DevID (IDevID) but also very restricted.
> 
> Thanks Adrian. I've opened #57 to track your comment.

And BTW, if you have any concrete suggestion about what to add and where, feel free to file a PR ;-)

**Pull request merged**
