### PR TITLE
Drop debris of partition id

### LINKED ISSUE #46: arm_psa_partition_id => psa-client-id
> Slight inconsistency through the file between client id (in block definition) & partition id here

Yeah, I can't recollect exactly how we ended up here, but we have also this: _`Note that the CDDL label used to be called arm_psa_partition_id.`_ in the Client ID subsection.  I'll raise an issue.

_Originally posted by @thomas-fossati in https://github.com/thomas-fossati/draft-psa-token/pull/45#discussion_r820509042_

### PR DESCRIPTION
**Pull request by thomas-fossati**
Fixes #46

### CODE REVIEW

**Comment by adrianlshaw** [comment]
Suggestion: keep it consistent with the naming of other "ID" claims we have, such as instance_id and implementation_id. So lower case and underscore before id: clientID -> client_id.

**Comment by adrianlshaw** [comment]
Also, why drop the "arm_psa_" prefix? I think we use this prefix to make it clear which claims are specific to PSA versus some generic claims in the CWT registry

**Comment by thomas-fossati** [comment]
> Suggestion: keep it consistent with the naming of other "ID" claims we have, such as instance_id and implementation_id. So lower case and underscore before id: clientID -> client_id.

hey Adrian, these changes are not "publicly" visible: they are limited to the internal test/consistency suite.  The only visible bit of this PR will be the dropping of the _"Note that the CDDL label used to be called arm_psa_partition_id."_ sentence from the bottom of [section 3.1.2](https://datatracker.ietf.org/doc/html/draft-tschofenig-rats-psa-token#section-3.1.2)

**Comment by thomas-fossati** [comment]
> Also, why drop the "arm_psa_" prefix? I think we use this prefix to make it clear which claims are specific to PSA versus some generic claims in the CWT registry

We have replaced the `arm_psa_` prefix and use `psa-` instead.

**Review by adrianlshaw — APPROVED** [review]
Ah, I hadn't noticed they were internal names. Then LGTM 👍

**Review by SimonFrost-Arm — COMMENTED** [review]
LGTM

**Pull request merged**
